### ISSUE TITLE
Add support for the Spinning Wheel.

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/WitcheryExtras#1]
Currently, I cannot add nor remove recipes for the Spinning Wheel.

- [x]  Add factory methods to get and set Spinning Wheel recipes.
- [x]  Add methods to create Spinning Wheel recipes.
- [x]  Add methods to remove Spinning Wheel recipes.
- [x]  Add handlers to base class for ease of use.

**Comment by Dream-Master** [comment]
@draknyte1 any news here ?

**Comment by Dream-Master** [comment]
@draknyte1 any news here? If you add it i will use the Mod 100%.
