### ISSUE TITLE
Add support for the Witches Oven.

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/WitcheryExtras#2]
Currently, I cannot add nor remove recipes for the Witches Oven.

- [x]  Add Recipe map based system for Witches Oven recipes.
- [x]  Make Witches Oven use new Recipe Map, or add new Oven.
- [ ]  Add custom rendering for new Oven.
- [ ]  Disable Old Oven.
- [ ]  Add new GUI for new Oven.
- [ ]  Add new slot to new GUI.
- [ ]  Add Forestry and BoP support to new Oven.

**Comment by Dream-Master** [comment]
@draknyte1 any news here ?

**Comment by Dream-Master** [comment]
@draknyte1 any news here? If you add it i will use the Mod 100%.
