### ISSUE TITLE
Add support for the Witches Cauldron. 

### ISSUE THREAD

**Issue by Dream-Master** [draknyte1/WitcheryExtras#5]
Add support for the Witches Cauldron.

**Comment by Dream-Master** [comment]
@draknyte1 any news here ?

**Comment by Dream-Master** [comment]
@draknyte1 any news here? If you add it i will use the Mod 100%.

**Comment by Dream-Master** [comment]
@draknyte1 consider to re open this? maybe my team do a pull request some day.

**Comment by draknyte1** [comment]
I’ll reopen it when that happens. 

Not going to have stale tickets for features I refuse to implement myself.
